<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="6" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="8790" started-at="2020-04-22T11:01:23 IST" finished-at="2020-04-22T11:01:32 IST">
    <groups>
    </groups>
    <test name="Test" duration-ms="8790" started-at="2020-04-22T11:01:23 IST" finished-at="2020-04-22T11:01:32 IST">
      <class name="com.api.restassured.TC006_GET_Authentication">
        <test-method status="PASS" signature="getAuthDetails()[pri:0, instance:com.api.restassured.TC006_GET_Authentication@6737fd8f]" name="getAuthDetails" duration-ms="776" started-at="2020-04-22T11:01:31 IST" finished-at="2020-04-22T11:01:31 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAuthDetails -->
      </class> <!-- com.api.restassured.TC006_GET_Authentication -->
      <class name="com.api.restassured.TC002_POST_Request">
        <test-method status="FAIL" signature="registerSuccess()[pri:0, instance:com.api.restassured.TC002_POST_Request@63e2203c]" name="registerSuccess" duration-ms="840" started-at="2020-04-22T11:01:29 IST" finished-at="2020-04-22T11:01:30 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [201] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [201] but found [200]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at com.api.restassured.TC002_POST_Request.registerSuccess(TC002_POST_Request.java:50)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerSuccess -->
      </class> <!-- com.api.restassured.TC002_POST_Request -->
      <class name="com.api.restassured.TC001_GET_Request">
        <test-method status="PASS" signature="getWeatherDetails()[pri:0, instance:com.api.restassured.TC001_GET_Request@1efed156]" name="getWeatherDetails" duration-ms="848" started-at="2020-04-22T11:01:30 IST" finished-at="2020-04-22T11:01:31 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getWeatherDetails -->
      </class> <!-- com.api.restassured.TC001_GET_Request -->
      <class name="com.api.restassured.TC004_GET_JsonValidate">
        <test-method status="PASS" signature="getWeatherDetails()[pri:0, instance:com.api.restassured.TC004_GET_JsonValidate@3b084709]" name="getWeatherDetails" duration-ms="3779" started-at="2020-04-22T11:01:23 IST" finished-at="2020-04-22T11:01:27 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getWeatherDetails -->
      </class> <!-- com.api.restassured.TC004_GET_JsonValidate -->
      <class name="com.api.restassured.TC005_GET_Json_Validate1">
        <test-method status="FAIL" signature="getWeatherDetails()[pri:0, instance:com.api.restassured.TC005_GET_Json_Validate1@3224f60b]" name="getWeatherDetails" duration-ms="1896" started-at="2020-04-22T11:01:27 IST" finished-at="2020-04-22T11:01:29 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Pass expected:<34 Degree celsius> but was:<30.52 Degree celsius>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Pass expected:<34 Degree celsius> but was:<30.52 Degree celsius>
at org.testng.AssertJUnit.fail(AssertJUnit.java:47)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:330)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:66)
at com.api.restassured.TC005_GET_Json_Validate1.getWeatherDetails(TC005_GET_Json_Validate1.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getWeatherDetails -->
      </class> <!-- com.api.restassured.TC005_GET_Json_Validate1 -->
      <class name="com.api.restassured.TC003_GET_Request">
        <test-method status="FAIL" signature="getGoogleMapTest()[pri:0, instance:com.api.restassured.TC003_GET_Request@72b6cbcc]" name="getGoogleMapTest" duration-ms="541" started-at="2020-04-22T11:01:31 IST" finished-at="2020-04-22T11:01:32 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<application/xml; charset=UTF-8> but was:<application/json>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<application/xml; charset=UTF-8> but was:<application/json>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:82)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:87)
at com.api.restassured.TC003_GET_Request.getGoogleMapTest(TC003_GET_Request.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getGoogleMapTest -->
      </class> <!-- com.api.restassured.TC003_GET_Request -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
